"""
Winter Olympics 2026 Milano-Cortina Events Data

Auto-generated by build_events.py from Olympics.com schedule data.
Contains all 116 medal events with dates and metadata.
Olympics run February 6-22, 2026.
Times are in Europe/Rome timezone (CET/UTC+1).
"""

from datetime import datetime
from dataclasses import dataclass
from typing import Literal

# All countries competing in the 2026 Winter Olympics (93 NOCs + ROC/Russia)
WINTER_OLYMPICS_COUNTRIES = [
    "Albania", "Andorra", "Argentina", "Armenia", "Australia", "Austria",
    "Azerbaijan", "Belgium", "Benin", "Bolivia", "Bosnia and Herzegovina", "Brazil",
    "Bulgaria", "Canada", "Chile", "China", "Chinese Taipei", "Colombia",
    "Croatia", "Cyprus", "Czech Republic", "Denmark", "Ecuador", "Eritrea",
    "Estonia", "Finland", "France", "Georgia", "Germany", "Great Britain",
    "Greece", "Guinea-Bissau", "Haiti", "Hong Kong", "Hungary", "Iceland",
    "India", "Individual Neutral Athletes", "Iran", "Ireland", "Israel", "Italy",
    "Jamaica", "Japan", "Kazakhstan", "Kenya", "Kosovo", "Kyrgyzstan",
    "Latvia", "Lebanon", "Liechtenstein", "Lithuania", "Luxembourg", "Madagascar",
    "Malaysia", "Malta", "Mexico", "Moldova", "Monaco", "Mongolia",
    "Montenegro", "Morocco", "Netherlands", "New Zealand", "Nigeria", "North Macedonia",
    "Norway", "Pakistan", "Philippines", "Poland", "Portugal", "Puerto Rico",
    "ROC/Russia", "Romania", "San Marino", "Saudi Arabia", "Serbia", "Singapore",
    "Slovakia", "Slovenia", "South Africa", "South Korea", "Spain", "Sweden",
    "Switzerland", "Thailand", "Trinidad and Tobago", "Turkey", "Ukraine", "United Arab Emirates",
    "United States", "Uruguay", "Uzbekistan", "Venezuela",
]

# Gender type
Gender = Literal["Men", "Women", "Mixed"]


@dataclass
class Event:
    """Represents a single Olympic event."""
    sport: str
    name: str
    gender: Gender
    first_round_date: datetime  # When the event starts (qualifying, first round, etc.)
    gold_medal_date: datetime   # When the gold medal is awarded

    @property
    def event_id(self) -> str:
        """Unique identifier for the event."""
        return f"{self.sport} - {self.name}"

    @property
    def display_name(self) -> str:
        """Display name with gender."""
        return f"{self.name}"


# All 116 events with schedule (auto-generated from Olympics.com)
EVENTS_DATA = [
    # Alpine Skiing (10 events)
    Event("Alpine Skiing", "Men's Downhill", "Men",
          datetime(2026, 2, 4, 11, 30), datetime(2026, 2, 7, 11, 30)),
    Event("Alpine Skiing", "Men's Team Combined", "Men",
          datetime(2026, 2, 9, 10, 30), datetime(2026, 2, 9, 14, 0)),
    Event("Alpine Skiing", "Men's Super-G", "Men",
          datetime(2026, 2, 11, 11, 30), datetime(2026, 2, 11, 11, 30)),
    Event("Alpine Skiing", "Men's Giant Slalom", "Men",
          datetime(2026, 2, 14, 10, 0), datetime(2026, 2, 14, 13, 30)),
    Event("Alpine Skiing", "Men's Slalom", "Men",
          datetime(2026, 2, 16, 10, 0), datetime(2026, 2, 16, 13, 30)),
    Event("Alpine Skiing", "Women's Downhill", "Women",
          datetime(2026, 2, 5, 11, 30), datetime(2026, 2, 8, 11, 30)),
    Event("Alpine Skiing", "Women's Team Combined", "Women",
          datetime(2026, 2, 9, 11, 30), datetime(2026, 2, 10, 14, 0)),
    Event("Alpine Skiing", "Women's Super-G", "Women",
          datetime(2026, 2, 12, 11, 30), datetime(2026, 2, 12, 11, 30)),
    Event("Alpine Skiing", "Women's Giant Slalom", "Women",
          datetime(2026, 2, 15, 10, 0), datetime(2026, 2, 15, 13, 30)),
    Event("Alpine Skiing", "Women's Slalom", "Women",
          datetime(2026, 2, 18, 10, 0), datetime(2026, 2, 18, 13, 30)),

    # Biathlon (11 events)
    Event("Biathlon", "Men's 20km Individual", "Men",
          datetime(2026, 2, 10, 13, 30), datetime(2026, 2, 10, 13, 30)),
    Event("Biathlon", "Men's 10km Sprint", "Men",
          datetime(2026, 2, 13, 14, 0), datetime(2026, 2, 13, 14, 0)),
    Event("Biathlon", "Men's 12.5km Pursuit", "Men",
          datetime(2026, 2, 15, 11, 15), datetime(2026, 2, 15, 11, 15)),
    Event("Biathlon", "Men's 4 x 7.5km Relay", "Men",
          datetime(2026, 2, 17, 14, 30), datetime(2026, 2, 17, 14, 30)),
    Event("Biathlon", "Men's 15km Mass Start", "Men",
          datetime(2026, 2, 20, 14, 15), datetime(2026, 2, 20, 14, 15)),
    Event("Biathlon", 'Mixed Relay 4 x 6km (M+W)', "Mixed",
          datetime(2026, 2, 8, 14, 5), datetime(2026, 2, 8, 14, 5)),
    Event("Biathlon", "Women's 15km Individual", "Women",
          datetime(2026, 2, 11, 14, 15), datetime(2026, 2, 11, 14, 15)),
    Event("Biathlon", "Women's 7.5km Sprint", "Women",
          datetime(2026, 2, 14, 14, 45), datetime(2026, 2, 14, 14, 45)),
    Event("Biathlon", "Women's 10km Pursuit", "Women",
          datetime(2026, 2, 15, 14, 45), datetime(2026, 2, 15, 14, 45)),
    Event("Biathlon", "Women's 4 x 6km Relay", "Women",
          datetime(2026, 2, 18, 14, 45), datetime(2026, 2, 18, 14, 45)),
    Event("Biathlon", "Women's 12.5km Mass Start", "Women",
          datetime(2026, 2, 21, 14, 15), datetime(2026, 2, 21, 14, 15)),

    # Bobsled (4 events)
    Event("Bobsled", '2-man', "Men",
          datetime(2026, 2, 12, 12, 50), datetime(2026, 2, 17, 21, 5)),
    Event("Bobsled", '4-man', "Men",
          datetime(2026, 2, 18, 10, 0), datetime(2026, 2, 22, 12, 15)),
    Event("Bobsled", "Women's Monobob", "Women",
          datetime(2026, 2, 12, 15, 30), datetime(2026, 2, 16, 21, 6)),
    Event("Bobsled", '2-woman', "Women",
          datetime(2026, 2, 17, 14, 0), datetime(2026, 2, 21, 21, 5)),

    # Cross-Country Skiing (12 events)
    Event("Cross-Country Skiing", "Men's 10km + 10km Skiathlon", "Men",
          datetime(2026, 2, 8, 12, 30), datetime(2026, 2, 8, 12, 30)),
    Event("Cross-Country Skiing", "Men's Sprint Classic", "Men",
          datetime(2026, 2, 10, 9, 57), datetime(2026, 2, 10, 13, 38)),
    Event("Cross-Country Skiing", "Men's 10km Interval Start Free", "Men",
          datetime(2026, 2, 13, 11, 45), datetime(2026, 2, 13, 11, 45)),
    Event("Cross-Country Skiing", "Men's 4 x 7.5km Relay", "Men",
          datetime(2026, 2, 15, 12, 0), datetime(2026, 2, 15, 12, 0)),
    Event("Cross-Country Skiing", "Men's Team Sprint Free", "Men",
          datetime(2026, 2, 18, 10, 15), datetime(2026, 2, 18, 12, 15)),
    Event("Cross-Country Skiing", "Men's 50km Mass Start Classic", "Men",
          datetime(2026, 2, 21, 11, 0), datetime(2026, 2, 21, 11, 0)),
    Event("Cross-Country Skiing", "Women's 10km + 10km Skiathlon", "Women",
          datetime(2026, 2, 7, 13, 0), datetime(2026, 2, 7, 13, 0)),
    Event("Cross-Country Skiing", "Women's Sprint Classic", "Women",
          datetime(2026, 2, 10, 9, 15), datetime(2026, 2, 10, 13, 24)),
    Event("Cross-Country Skiing", "Women's 10km Interval Start Free", "Women",
          datetime(2026, 2, 12, 13, 0), datetime(2026, 2, 12, 13, 0)),
    Event("Cross-Country Skiing", "Women's 4 x 7.5km Relay", "Women",
          datetime(2026, 2, 14, 12, 0), datetime(2026, 2, 14, 12, 0)),
    Event("Cross-Country Skiing", "Women's Team Sprint Free", "Women",
          datetime(2026, 2, 18, 9, 45), datetime(2026, 2, 18, 11, 45)),
    Event("Cross-Country Skiing", "Women's 50km Mass Start Classic", "Women",
          datetime(2026, 2, 22, 10, 0), datetime(2026, 2, 22, 10, 0)),

    # Curling (3 events)
    Event("Curling", 'Men', "Men",
          datetime(2026, 2, 11, 19, 5), datetime(2026, 2, 21, 19, 5)),
    Event("Curling", 'Mixed Doubles', "Mixed",
          datetime(2026, 2, 4, 19, 5), datetime(2026, 2, 10, 18, 5)),
    Event("Curling", 'Women', "Women",
          datetime(2026, 2, 12, 9, 5), datetime(2026, 2, 22, 11, 5)),

    # Figure Skating (5 events)
    Event("Figure Skating", 'Men Single Skating', "Men",
          datetime(2026, 2, 10, 18, 30), datetime(2026, 2, 13, 19, 0)),
    Event("Figure Skating", 'Team Event', "Mixed",
          datetime(2026, 2, 6, 9, 55), datetime(2026, 2, 8, 21, 55)),
    Event("Figure Skating", 'Ice Dance', "Mixed",
          datetime(2026, 2, 9, 19, 20), datetime(2026, 2, 11, 19, 30)),
    Event("Figure Skating", 'Pair Skating', "Mixed",
          datetime(2026, 2, 15, 19, 45), datetime(2026, 2, 16, 20, 0)),
    Event("Figure Skating", 'Women Single Skating', "Women",
          datetime(2026, 2, 17, 18, 45), datetime(2026, 2, 19, 19, 0)),

    # Freestyle Skiing (15 events)
    Event("Freestyle Skiing", "Men's Freeski Slopestyle", "Men",
          datetime(2026, 2, 7, 14, 0), datetime(2026, 2, 10, 13, 28)),
    Event("Freestyle Skiing", "Men's Moguls", "Men",
          datetime(2026, 2, 10, 11, 15), datetime(2026, 2, 12, 12, 55)),
    Event("Freestyle Skiing", "Men's Dual Moguls", "Men",
          datetime(2026, 2, 15, 10, 30), datetime(2026, 2, 15, 11, 48)),
    Event("Freestyle Skiing", "Men's Freeski Big Air", "Men",
          datetime(2026, 2, 15, 19, 30), datetime(2026, 2, 17, 20, 17)),
    Event("Freestyle Skiing", "Men's Aerials", "Men",
          datetime(2026, 2, 17, 13, 30), datetime(2026, 2, 19, 12, 30)),
    Event("Freestyle Skiing", "Men's Freeski Halfpipe", "Men",
          datetime(2026, 2, 19, 10, 30), datetime(2026, 2, 20, 20, 28)),
    Event("Freestyle Skiing", "Men's Ski Cross", "Men",
          datetime(2026, 2, 21, 10, 0), datetime(2026, 2, 21, 13, 15)),
    Event("Freestyle Skiing", 'Mixed Team Aerials', "Mixed",
          datetime(2026, 2, 21, 10, 45), datetime(2026, 2, 21, 11, 45)),
    Event("Freestyle Skiing", "Women's Freeski Slopestyle", "Women",
          datetime(2026, 2, 7, 10, 30), datetime(2026, 2, 9, 13, 28)),
    Event("Freestyle Skiing", "Women's Moguls", "Women",
          datetime(2026, 2, 10, 14, 15), datetime(2026, 2, 11, 14, 55)),
    Event("Freestyle Skiing", "Women's Dual Moguls", "Women",
          datetime(2026, 2, 14, 10, 30), datetime(2026, 2, 14, 11, 48)),
    Event("Freestyle Skiing", "Women's Freeski Big Air", "Women",
          datetime(2026, 2, 14, 19, 30), datetime(2026, 2, 16, 20, 17)),
    Event("Freestyle Skiing", "Women's Aerials", "Women",
          datetime(2026, 2, 17, 10, 45), datetime(2026, 2, 18, 12, 30)),
    Event("Freestyle Skiing", "Women's Freeski Halfpipe", "Women",
          datetime(2026, 2, 19, 19, 30), datetime(2026, 2, 21, 20, 28)),
    Event("Freestyle Skiing", "Women's Ski Cross", "Women",
          datetime(2026, 2, 20, 10, 0), datetime(2026, 2, 20, 13, 15)),

    # Ice Hockey (2 events)
    Event("Ice Hockey", 'Men', "Men",
          datetime(2026, 2, 11, 16, 40), datetime(2026, 2, 22, 14, 10)),
    Event("Ice Hockey", 'Women', "Women",
          datetime(2026, 2, 5, 12, 10), datetime(2026, 2, 19, 19, 10)),

    # Luge (5 events)
    Event("Luge", "Men's Singles", "Men",
          datetime(2026, 2, 4, 20, 0), datetime(2026, 2, 8, 18, 34)),
    Event("Luge", "Men's Doubles", "Men",
          datetime(2026, 2, 8, 13, 30), datetime(2026, 2, 11, 19, 44)),
    Event("Luge", 'Team Relay', "Mixed",
          datetime(2026, 2, 12, 18, 30), datetime(2026, 2, 12, 18, 30)),
    Event("Luge", "Women's Singles", "Women",
          datetime(2026, 2, 5, 17, 0), datetime(2026, 2, 10, 18, 34)),
    Event("Luge", "Women's Doubles", "Women",
          datetime(2026, 2, 8, 14, 46), datetime(2026, 2, 11, 18, 53)),

    # Nordic Combined (3 events)
    Event("Nordic Combined", 'Individual Gundersen Normal Hill/10km', "Men",
          datetime(2026, 2, 11, 9, 10), datetime(2026, 2, 11, 13, 45)),
    Event("Nordic Combined", 'Individual Gundersen Large Hill/10km', "Men",
          datetime(2026, 2, 17, 9, 10), datetime(2026, 2, 17, 13, 45)),
    Event("Nordic Combined", 'Team Sprint', "Men",
          datetime(2026, 2, 19, 9, 10), datetime(2026, 2, 19, 14, 0)),

    # Short Track Speed Skating (9 events)
    Event("Short Track Speed Skating", "Men's 1000m", "Men",
          datetime(2026, 2, 10, 11, 10), datetime(2026, 2, 12, 21, 48)),
    Event("Short Track Speed Skating", "Men's 1500m", "Men",
          datetime(2026, 2, 14, 20, 15), datetime(2026, 2, 14, 22, 42)),
    Event("Short Track Speed Skating", "Men's 500m", "Men",
          datetime(2026, 2, 16, 11, 17), datetime(2026, 2, 18, 21, 32)),
    Event("Short Track Speed Skating", "Men's 5000m Relay", "Men",
          datetime(2026, 2, 16, 12, 6), datetime(2026, 2, 20, 21, 30)),
    Event("Short Track Speed Skating", 'Mixed Team Relay', "Mixed",
          datetime(2026, 2, 10, 11, 59), datetime(2026, 2, 10, 13, 10)),
    Event("Short Track Speed Skating", "Women's 500m", "Women",
          datetime(2026, 2, 10, 10, 30), datetime(2026, 2, 12, 21, 35)),
    Event("Short Track Speed Skating", "Women's 1000m", "Women",
          datetime(2026, 2, 14, 21, 1), datetime(2026, 2, 16, 12, 47)),
    Event("Short Track Speed Skating", "Women's 3000m Relay", "Women",
          datetime(2026, 2, 14, 22, 5), datetime(2026, 2, 18, 21, 0)),
    Event("Short Track Speed Skating", "Women's 1500m", "Women",
          datetime(2026, 2, 20, 20, 15), datetime(2026, 2, 20, 22, 7)),

    # Skeleton (3 events)
    Event("Skeleton", 'Men', "Men",
          datetime(2026, 2, 9, 10, 30), datetime(2026, 2, 13, 21, 5)),
    Event("Skeleton", 'Mixed Team', "Mixed",
          datetime(2026, 2, 15, 18, 0), datetime(2026, 2, 15, 18, 0)),
    Event("Skeleton", 'Women', "Women",
          datetime(2026, 2, 9, 8, 0), datetime(2026, 2, 14, 19, 35)),

    # Ski Jumping (6 events)
    Event("Ski Jumping", "Men's NH Individual", "Men",
          datetime(2026, 2, 9, 18, 0), datetime(2026, 2, 9, 20, 12)),
    Event("Ski Jumping", "Men's LH Individual", "Men",
          datetime(2026, 2, 14, 17, 30), datetime(2026, 2, 14, 19, 57)),
    Event("Ski Jumping", "Men's Super Team", "Men",
          datetime(2026, 2, 16, 18, 0), datetime(2026, 2, 16, 20, 20)),
    Event("Ski Jumping", 'Mixed Team', "Mixed",
          datetime(2026, 2, 10, 17, 30), datetime(2026, 2, 10, 20, 0)),
    Event("Ski Jumping", "Women's NH Individual", "Women",
          datetime(2026, 2, 7, 17, 45), datetime(2026, 2, 7, 19, 57)),
    Event("Ski Jumping", "Women's LH Individual", "Women",
          datetime(2026, 2, 15, 17, 35), datetime(2026, 2, 15, 19, 57)),

    # Ski Mountaineering (3 events)
    Event("Ski Mountaineering", "Men's Sprint", "Men",
          datetime(2026, 2, 19, 10, 30), datetime(2026, 2, 19, 14, 15)),
    Event("Ski Mountaineering", 'Mixed Relay', "Mixed",
          datetime(2026, 2, 21, 13, 30), datetime(2026, 2, 21, 13, 30)),
    Event("Ski Mountaineering", "Women's Sprint", "Women",
          datetime(2026, 2, 19, 9, 50), datetime(2026, 2, 19, 13, 55)),

    # Snowboard (11 events)
    Event("Snowboard", "Men's Snowboard Big Air", "Men",
          datetime(2026, 2, 5, 19, 30), datetime(2026, 2, 7, 20, 17)),
    Event("Snowboard", "Men's Parallel Giant Slalom", "Men",
          datetime(2026, 2, 8, 9, 30), datetime(2026, 2, 8, 14, 39)),
    Event("Snowboard", "Men's Snowboard Halfpipe", "Men",
          datetime(2026, 2, 11, 19, 30), datetime(2026, 2, 13, 20, 28)),
    Event("Snowboard", "Men's Snowboard Cross", "Men",
          datetime(2026, 2, 12, 10, 0), datetime(2026, 2, 12, 15, 1)),
    Event("Snowboard", "Men's Snowboard Slopestyle", "Men",
          datetime(2026, 2, 16, 14, 0), datetime(2026, 2, 18, 13, 28)),
    Event("Snowboard", 'Mixed Team Snowboard Cross', "Mixed",
          datetime(2026, 2, 15, 13, 45), datetime(2026, 2, 15, 14, 40)),
    Event("Snowboard", "Women's Parallel Giant Slalom", "Women",
          datetime(2026, 2, 8, 9, 0), datetime(2026, 2, 8, 14, 29)),
    Event("Snowboard", "Women's Snowboard Big Air", "Women",
          datetime(2026, 2, 8, 19, 30), datetime(2026, 2, 9, 20, 17)),
    Event("Snowboard", "Women's Snowboard Halfpipe", "Women",
          datetime(2026, 2, 11, 10, 30), datetime(2026, 2, 12, 20, 28)),
    Event("Snowboard", "Women's Snowboard Cross", "Women",
          datetime(2026, 2, 13, 10, 0), datetime(2026, 2, 13, 14, 46)),
    Event("Snowboard", "Women's Snowboard Slopestyle", "Women",
          datetime(2026, 2, 16, 10, 30), datetime(2026, 2, 17, 13, 54)),

    # Speed Skating (14 events)
    Event("Speed Skating", "Men's 5000m", "Men",
          datetime(2026, 2, 8, 16, 0), datetime(2026, 2, 8, 16, 0)),
    Event("Speed Skating", "Men's 1000m", "Men",
          datetime(2026, 2, 11, 18, 30), datetime(2026, 2, 11, 18, 30)),
    Event("Speed Skating", "Men's 10000m", "Men",
          datetime(2026, 2, 13, 16, 0), datetime(2026, 2, 13, 16, 0)),
    Event("Speed Skating", "Men's 500m", "Men",
          datetime(2026, 2, 14, 17, 0), datetime(2026, 2, 14, 17, 0)),
    Event("Speed Skating", "Men's Team Pursuit", "Men",
          datetime(2026, 2, 15, 16, 0), datetime(2026, 2, 17, 16, 28)),
    Event("Speed Skating", "Men's 1500m", "Men",
          datetime(2026, 2, 19, 16, 30), datetime(2026, 2, 19, 16, 30)),
    Event("Speed Skating", "Men's Mass Start", "Men",
          datetime(2026, 2, 21, 15, 0), datetime(2026, 2, 21, 16, 40)),
    Event("Speed Skating", "Women's 3000m", "Women",
          datetime(2026, 2, 7, 16, 0), datetime(2026, 2, 7, 16, 0)),
    Event("Speed Skating", "Women's 1000m", "Women",
          datetime(2026, 2, 9, 17, 30), datetime(2026, 2, 9, 17, 30)),
    Event("Speed Skating", "Women's 5000m", "Women",
          datetime(2026, 2, 12, 16, 30), datetime(2026, 2, 12, 16, 30)),
    Event("Speed Skating", "Women's Team Pursuit", "Women",
          datetime(2026, 2, 14, 16, 0), datetime(2026, 2, 17, 16, 47)),
    Event("Speed Skating", "Women's 500m", "Women",
          datetime(2026, 2, 15, 17, 3), datetime(2026, 2, 15, 17, 3)),
    Event("Speed Skating", "Women's 1500m", "Women",
          datetime(2026, 2, 20, 16, 30), datetime(2026, 2, 20, 16, 30)),
    Event("Speed Skating", "Women's Mass Start", "Women",
          datetime(2026, 2, 21, 15, 50), datetime(2026, 2, 21, 17, 15)),
]


def get_all_events() -> list[Event]:
    """Return all events."""
    return EVENTS_DATA


def get_events_by_sport() -> dict[str, list[Event]]:
    """Return events grouped by sport."""
    sports = {}
    for event in EVENTS_DATA:
        if event.sport not in sports:
            sports[event.sport] = []
        sports[event.sport].append(event)
    return sports


def get_sports() -> list[str]:
    """Return list of all sports."""
    return sorted(set(e.sport for e in EVENTS_DATA))


def get_countries() -> list[str]:
    """Return list of countries for prediction dropdowns."""
    return WINTER_OLYMPICS_COUNTRIES


def filter_events(
    events: list[Event],
    sport: str | None = None,
    gender: Gender | None = None
) -> list[Event]:
    """Filter events by sport and/or gender."""
    result = events
    if sport:
        result = [e for e in result if e.sport == sport]
    if gender:
        result = [e for e in result if e.gender == gender]
    return result


def sort_events_by_date(events: list[Event], by_gold_medal: bool = False) -> list[Event]:
    """Sort events by date (first round or gold medal)."""
    if by_gold_medal:
        return sorted(events, key=lambda e: e.gold_medal_date)
    return sorted(events, key=lambda e: e.first_round_date)

